### ISSUE TITLE
Change all available references from `Kokkos::View` to `StridedVector` or `StridedMatrix`

### ISSUE THREAD

**Issue by dannys4** [MeasureTransport/MParT#155]
For the Julia bindings, I've realized that C++ really *does not* like working with both `StridedVector<double, Kokkos::HostSpace>` and `Kokkos::View<double*, Kokkos::HostSpace>`. I do not quite understand why, but a simple solution is to just make everything called `Kokkos::View` into a `StridedVector` or `StridedMatrix`. Give me an hour and a regex reference website, and I'll get this sorted out.

**Comment by mparno** [comment]
Hey @dannys4!  What issues are you seeing on the c++ side?  

Unless I'm missing some complication, I don't think we actually want to convert every use of `Kokkos::View` to either a `StridedVector` or `StridedMatrix`.   The strided types are convenient for function arguments because they can accommodate row-major, column-major, and sliced matrices/vectors.  However, they are sometimes less efficient (because the stride isn't known at compile time) and are more complicated to construct (because you have to manually specify the stride type).    Kokkos will also choose a default layout that is best suited for the execution space being used (e.g., OpenMP or CUDA) and using the `Strided` variants will prevent us from using that default.
