### ISSUE TITLE
MATLAB crash on map inverse

### ISSUE THREAD

**Issue by jgrashorn** [MeasureTransport/MParT#283]
After optimizing the map parameters to approximate some posterior function I found that MATLAB crashes during map inversion for PDF calculations. Carefully choosing where to calculate the PDF (so that it's in the support of the posterior) seems to work somewhat well, however it also crashes for inputs that are reasonably close to the support (or at least should be from the true posterior).
I tried this with 2021b and 2022b, just to be sure. 

[crashlog.txt](https://github.com/MeasureTransport/MParT/files/10066759/crashlog.txt)

MWE:
```
num_threads = 8;
KokkosInitialize(num_threads);

opts = MapOptions;
total_order = 2;

wOpt = [-1.557,-3.632,-0.0374,-0.3667, -5.183,-0.4099,-0.008745,0.2563, -0.006456,...
    -0.4069,-6.117,-0.09979,-0.2780, 0.3246, 0.03077, -0.04134, 0.1486, -0.07189,...
    0.01435, 0.5120,-5.532, -0.2009, -0.06512, -0.4669,0.003381, 0.4699, 0.5035,...
    -0.01449, -0.02010, 0.03065, 0.2347, -0.01816, 0.1772,-0.02076];

tri_map = CreateTriangular(4,4,total_order,opts);
tri_map.SetCoeffs(wOpt);

x = [-2,-2,0,0]'; 
inv = tri_map.Inverse(x,x); % works fine

x = [-1,-.2,0,0]'; 
inv = tri_map.Inverse(x,x); % MATLAB crashes
```

**Comment by rubiop** [comment]
Thanks @jgrashorn for reporting this bug! I was also able to reproduce your error, that's definitely not the expected behavior. We will let you know when this is fixed.

**Comment by jgrashorn** [comment]
Sure, happy to help! I was hoping that there was something wrong with my installation, that might have been easier.
Thanks for your work!

**Comment by michael-c-brennan** [comment]
Hi @jgrashorn! It looks like the problem is that some of the components of your map are flat in their end behavior, which makes computing the inverse unstable (here is a plot of the second component as an example) 
![Figure_1](https://user-images.githubusercontent.com/58437918/203414435-a577a2a1-3c88-48fa-883e-26d63854ce83.png)

We have some ideas for how to prevent this long term--in the short term, try adding the `basisLB` and `basisUB` options, which force the map to be linear outside of the interval `[basisLB, basisUB]`. For example:
```
opts = MapOptions;
opts.basisLB=-3;
opts.basisUB=3;
```
Also, would you mind sharing how you optimized the map? I'm hope to learn about when this behavior happens.

**Comment by michael-c-brennan** [comment]
If you don't mind that would be great!
