### ISSUE TITLE
Consistent names for gradient method

### ISSUE THREAD

**Issue by michael-c-brennan** [MeasureTransport/MParT#301]
Our nomenclature for gradient methods is inconsistent. We use `Gradient` and `CoeffGrad` for the gradients of the map evaluation, but `LogDeterminantInputGrad` and `LogDeterminantCoeffGrad` for the gradients of the log-determinant Jacobian. More gradient functions will be implemented for the distribution class as well (#300). I think we should make all the names match the pattern `FunctionName[Input/Coeff]Grad`.

**Comment by dannys4** [comment]
I completely agree with a standard pattern `[Function][Input/Coeff]Grad`. I changed #298 and #300 to reflect this standard pattern.

**Comment by dannys4** [comment]
@mparno how would you feel about calling `Gradient` "deprecated" and it just calls a function `InputGrad`, which is exactly what `Gradient` used to do. This should prevent any previous code from breaking (hopefully :/), while still moving toward a consistent naming scheme.

Also, did we want to keep "coeff" or move toward "param" (I think we discussed this offline since the parameters are not necessarily best interpreted as coefficients)

**Comment by mparno** [comment]
I like the deprecated approach and the change to params.  So we'd end up with an `InputGrad` function and a `ParamGrad` function?

**Comment by dannys4** [comment]
Yes, which would deprecate `Gradient` and `CoeffGrad`. Similarly, we'd have `LogDeterminantInputGrad` and `LogDeterminantParamGrad` (where the former is unchanged from the current API).

**Comment by dannys4** [comment]
After discussing this with @mparno offline, it's been decided that we should probably just keep things as they are and add better documentation. Changing the issue to reflect this.
