### ISSUE TITLE
Unpredictable MultiIndexSet behavior (Julia)

### ISSUE THREAD

**Issue by dannys4** [MeasureTransport/MParT#332]
```julia
function banana_ND_msets(dim::Int)
    msets = Vector{Matrix{Int}}(undef, dim)
    first_mset = collect(reshape([0; 1], 2, 1))
    general_mset = [0 0; 0 1; 1 0; 2 0]
    mset_len = size(general_mset, 1)
    msets[1] = first_mset
    for j = 2:dim
        msets[j] = [zeros(mset_len, j - 2) general_mset]
    end
    msets
end
function MSetTest()
    dim = 8
    msets = banana_ND_msets(dim)
    f_msets = [Fix(MultiIndexSet(mset),true) for mset in msets]
    f_msets_loop = []
    for mset in msets
        mset_mt = MultiIndexSet(copy(mset))
        f_mset_mt = Fix(mset_mt,true)
        push!(f_msets_loop, f_mset_mt)
    end
    size_msets = [size(mset,1) for mset in msets]
    size_f_msets = [Int(size(f_mset)) for f_mset in f_msets]
    size_f_msets_loop = [Int(size(f_mset)) for f_mset in f_msets_loop]
    println(size_msets)
    println(size_f_msets)
    println(size_f_msets_loop)
end
MSetTest()
```
This theoretically should print three vectors, which have first element 2 and the rest are 4. The first printed line is correct, whereas the latter printed lines is what MParT will find. For some reason, creating the multiindex sets and fixing them in these iterables makes the output unpredictable. Example output:
```
[2, 4, 4, 4, 4, 4, 4, 4]
[2, 4, 4, 4, 3, 4, 4, 4]
[2, 4, 4, 4, 3, 4, 4, 4]
```

**Comment by dannys4** [comment]
there's no current way of "unfixing" FixedMultiIndexSet objects in the julia bindings, and I don't observe this behavior in python.

**Comment by dannys4** [comment]
Further, if I create an "unrolled" version of this, as seen below, I still observe this behavior.
```julia
    f_msets_static = [Fix(MultiIndexSet(copy(msets[1])),true)
                      Fix(MultiIndexSet(copy(msets[2])),true)
                      Fix(MultiIndexSet(copy(msets[3])),true)
                      Fix(MultiIndexSet(copy(msets[4])),true)
                      Fix(MultiIndexSet(copy(msets[5])),true)
                      Fix(MultiIndexSet(copy(msets[6])),true)
                      Fix(MultiIndexSet(copy(msets[7])),true)
                      Fix(MultiIndexSet(copy(msets[8])),true)]
```

**Comment by dannys4** [comment]
This is a problem in the call to the `MultiIndexSet` somehow. If I just look at a variable `msets_mt = [MultiIndexSet(mset) for mset in msets]`, this predicts the behavior of `Fix`. I suspect this is a memory access problem in the `JuliaToEigenMat::JlArrayConversions.cpp` function.

**Comment by mparno** [comment]
I'd be surprised if the issue was with `JuliaToEigenMat`.   To me, that issue would arise when you construct the `MultiIndexSet` on its own even before calling `Fix`.    Given that the size of the `FixedMultiIndexSet` is different than the `MultiIndexSet`, I would guess there is something happening in the conversion that you weren't expecting.   Does the multiindexset where the discrepency occurs (fixed has size 3, but full has size 4) contain a multiindex of all zeros?    That might be getting stripped in the `MultiIndexSet` -> `FixedMultiIndexSet` compression.

**Comment by mparno** [comment]
Nevermind, I see what you're doing.  There's still only one zero multiindex per set, just with increasing dimensions.

**Comment by mparno** [comment]
You're right Danny, the issue seems to be in the construction of the `MultiIndexSet` itself and has nothing to do with `Fix()`.   Here's a stripped down example
```julia
function MSetTest()
    dim = 8
    msets_list = banana_ND_msets(dim)
    msets = [MultiIndexSet(m) for m in msets_list]

    println("Truth:         ", [size(mset,1) for mset in msets_list])
    println("MultiIndexSet: ", [Int(Size(m)) for m in msets])
end
```

This randomly alternates between the correct output and what Danny was seeing:
```
Truth:         [2, 4, 4, 4, 4, 4, 4, 4]
MultiIndexSet: [2, 4, 4, 4, 3, 4, 4, 4]
```

**Comment by mparno** [comment]
@dannys4 I think I found the issue on [line 43 of JlArrayConversions.cpp](https://github.com/MeasureTransport/MParT/blob/f6c3ebd3c20ce35210a5e74845866ec0a978551e/bindings/julia/src/JlArrayConversions.cpp#L43).   The line is:
```cpp
Eigen::Map<const Eigen::Matrix<int,Eigen::Dynamic, Eigen::Dynamic>,0,Eigen::OuterStride<>>(mptr, rows, cols, Eigen::OuterStride<>(std::max(rows,cols)))
```
where `std::max(rows,cols)` is setting the size of the outer stride.  This definitely shouldn't be the maximum of the rows or columns.   Julia stores matrices in column major layout, so the outer stride should be the number of elements between columns.  If the the memory of the Julia array is contiguous, which I think we can assume it is, then the outer stride should always be `rows`.    Using the max also explains why this issue seems to happen when we have dimension >5.  At that point there are more columns than rows in the matrix containing the multiindices.    

I'm not quite sure what the workflow is for updating the Julia bindings.   Would you be able to take a stab at fixing this when you have a chance?

**Comment by dannys4** [comment]
Yeah i thought it was something in that line. Turns out copy pasting your eigen code only gets me so far. I'll take a gander when I get the chance.

**Comment by mparno** [comment]
We should double check the original code you copied too.  I might have made the mistake there as well.

**Comment by dannys4** [comment]
The only other times that we did this are in ArrayConversions.h at lines 565 and 573. I _think_ these are implemented correctly-- we take the outer stride as whichever stride is not consecutive. I misunderstood this the first time I was implementing the Julia bindings, unfortunately :/.
